### ISSUE TITLE
Example with the default video not working in iOS

### ISSUE THREAD

**Issue by mchlsndrn** [polarby/render#12]
**Describe the bug**
The example works fine using the Android emulator.
The iOS Simulator throws a generic error
"PlatformException (PlatformException(VideoError, Failed to load video: Operation Stopped, null, null))"
when trying to load the default video
"https://www.fluttercampus.com/video.mp4"
but not when using the following video
"https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4"
or the other 1 minute sample (https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4).

The Simulator image is "iPhone 14 Pro Max".

**To Reproduce**
1. Simply open the example on MacOs and built to the iOS Simulator
"PlatformException (PlatformException(VideoError, Failed to load video: Operation Stopped, null, null))"

**Expected behavior**
No errors, just like on Android.

**Platform (please complete the following information):**
render: ^0.1.2
video_player: ^2.5.2

Moving to the latest version of video_player 2.6.0 doesn't solve the problem.

**Comment by polarby** [comment]
This seems to be a `VideoPlayer`related problem, no? Are you suggesting changing the example video URL, as it may contain an unreadable format for ios?

**Comment by mchlsndrn** [comment]
I think that's the issue, an unreadable format for iOS.
The other video works.

**Unrelated: could you please reopen Issue #11 ?**
The proposed solution / workaround does not work ... I've also posted repro steps.

**Comment by polarby** [comment]
Updated with 29ec060bc4b40a9d602a368fcdbcaafcb28d7a8e, pub.dev update on next release. Thanks for pointing that out!
