### ISSUE TITLE
Using captureMotionWithStream() with a flutter_map

### ISSUE THREAD

**Issue by mchlsndrn** [polarby/render#13]
I'm trying to export a video via captureMotionWithStream() of an animated map created using the [flutter_map](https://pub.dev/packages/flutter_map) package.
Flutter_map allows to create maps in flutter using raster tiles, which in my case are stored offline on the device.
The capture works but, especially during fast movements moving around on the map, some tiles aren't yet loaded.
Would it be possible to wait an additional arbitrary duration in milliseconds for each captured frame / tick?

**Comment by polarby** [comment]
This would increase the capturing time enormously. I see also no other application for this. This plugin is simply for capturing the widgets that are currently displayed. If the content is not loaded properly before, this seems to be unrelated to this plugin?! I will close this issue, but please reopen it, if you feel this is no a proper decision.
