### ISSUE TITLE
Unhandled Exception: type 'RenderError' is not a subtype of type 'RenderResult' in type cast

### ISSUE THREAD

**Issue by jerrypaulsam** [polarby/render#20]
I am getting this error in Android phones. `Unhandled Exception: type 'RenderError' is not a subtype of type 'RenderResult' in type cast`

```
RenderError(timestamp: 0:00:06.225000, exception: RenderException([Ffmpeg execution error] [amediacodec @ 0xb400007cde9f4b80] android.media.MediaCodec$CodecException: Error 0xffffffc3
I/flutter (28087): , details: null), fatal: true)
```

The code:
```
final stream = await stream.firstWhere((event) => event.isResult || event.isFatalError);
result = stream as RenderResult; // The error is being thrown here
```

Please do help!

Thanks

**Comment by polarby** [comment]
Note that `result.isResult` the same is as `result is RenderResult`.
In your case `result` is an error and therefore cannot be assumed to be `RenderResult `.

What you have to do is, check if the operation is successful (return is `RenderResult`) or unsuccessful (return type is an `RenderFatalError`).

**Comment by jerrypaulsam** [comment]
I was able to solve this error by manually specifying the video codec libx264 in every ffmpeg operation. Without it the operation were failing and returning the error.

**Comment by polarby** [comment]
You just eliminated the error (- which is great👍🏻) but I highly recommend you to test for errors as well! 
This way your app won’t stop working unexpectedly, but you can tell the user what went wrong.

**Comment by jerrypaulsam** [comment]
Hello @polarby 

I tested the package with different devices, it isn't working with Oneplus 8 pro, redmi note , and realme device but is working fine in Samsung devices and iphones.

I am getting the mediacodec error thrown by ffmpeg:
`RenderError(timestamp: 0:00:06.796000, exception: RenderException([Ffmpeg execution error] [amediacodec @ 0xb400007e4cefaa00] android.media.MediaCodec$CodecException: Error 0xffffffc3
I/flutter (15303): , details: null), fatal: true)`

Is there a workaround for this? I tried with captureMotion and captureMotionWithStream and getting the same error in these devices.

captureImage works fine in all devices.

**Comment by polarby** [comment]
Oh! That sure is a different issue! Which we might need to move to another issue.

I am unaware of codec issue on certain devices -> especially what’s weird is that captureImage works. Must be something with video processing. Did you try to put a different output format?

Could you please open a new issue and set the logLevel to debug, so we can see the whole process what is going wrong?!

**Comment by jerrypaulsam** [comment]
Hello

Thanks for the response. 

I opened a new issue.
