### ISSUE TITLE
Hide and make widget invisible when using captureMotionWithStream()

### ISSUE THREAD

**Issue by qiwen98** [polarby/render#22]
Hi, thanks for the great work!

Is it possible to hide the Render widget (e.g. the AnimatedExampleWidget in main.dart) when using the captureMotionWithStream, 
I wish to render and record the widget in the background by not showing the rendering process. 
CaptureMotionFromWidgetWithStream sounds like the feature I want, but I have no idea how to modify it in main.dart.
I would appreciate any help.

**Comment by polarby** [comment]
Sure. `CaptureMotionFromWidgetWithStream ` has a widget parameter input. This function will provide your widget a off-screen context, from which it is being build.

Thefore you can simply do:
```dart
final stream = controller.captureMotionFromWidgetWithStream(AnimatedExampleWidget(), ...);
```

This code is not written in your widget tree, but you can put it in your initState() for example.

**Comment by polarby** [comment]
If you display the animation don't use ...fromWidget. Nonetheless I believe that is an issue in your code. Please try your problem with a default widget and compare if the issue still arises. 
I am unable to determine what's going wrong just from your text, but you might be required to preload the data in your initstate and then pass it to your to-be-rendered widget.

**Comment by Sagar-KC-3082** [comment]
var stream = _renderController.captureMotionFromWidgetWithStream(
              context,
              Scaffold(
                body: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Image.asset(
                      'assets/images/template2/lord_ganesh.png',
                      height: 240,
                      width: 240,
                      fit: BoxFit.contain,
                    ),
                  ],
                ),
              ),
              const Duration(seconds: 5));
              
             This always give "No MediaQuery widget ancestor found." Error

**Comment by Sagar-KC-3082** [comment]
I have to use the animations and render them in background.
Using captureMotionFromWidgetWithStream() creates certain issue..
Is there any way I can communicate with you ?? Would be a great help to me.
