### ISSUE TITLE
NoSupport [sizeAndRate.support, 324x624x10.274868965148926] [OMX.IMG.MSVDX.Decoder.MPEG4, video/mp4v-es] [HWNXT, HUAWEI NXT-TL00, HUAWEI, 26]

### ISSUE THREAD

**Issue by JosonJiang** [polarby/render#23]
NoSupport [sizeAndRate.support, 324x624x10.274868965148926] [OMX.IMG.MSVDX.Decoder.MPEG4, video/mp4v-es] [HWNXT, HUAWEI NXT-TL00, HUAWEI, 26]

W/HwExtendedUtils( 1672): hw configLocalPlayBack err = -1010
E/ACodec  ( 1672): [OMX.IMG.MSVDX.Decoder.MPEG4] setPortMode on output to DynamicANWBuffer failed w/ err -1010
W/ACodec  ( 1672): [OMX.IMG.MSVDX.Decoder.MPEG4] prepareForAdaptivePlayback failed w/ err -1010
I/HwExtendedCodec( 1672): mime is [video/mp4v-es] at setVideoFormat
I/ACodec  ( 1672): codec does not support config priority (err -1010)
I/ACodec  ( 1672): onStart

when i use the example and  add the  

```dart                       
final motionResult = await renderController.captureMotion(
                          const Duration(seconds: 15),
                          format: MotionFormat.mp4,
                          settings: const MotionSettings(pixelRatio: 3),
                        );
                        displayResult(motionResult,true);

```

**Comment by polarby** [comment]
我真不知道您的問題，下次請描寫詳細的。若果你用別的電話這個問題也出現嗎？只是一個華為的問題？不好意思，我不能複製！

**Comment by JosonJiang** [comment]
> 我真不知道您的問題，下次請描寫詳細的。若果你用別的電話這個問題也出現嗎？只是不是一個華為的問題？不好意思，我不能複製！

哈哈 谢谢你用中文回复我! 这个问题不是很重要,就是警告错误,我关闭了

Thank you so much, you replay with Chinese!
