### ISSUE TITLE
Select file directory

### ISSUE THREAD

**Issue by xOldeVx** [polarby/render#33]
I see the package save the record files in the app cache directory and with some weird name, is it possible to choose another directory and select another file name?

**Comment by polarby** [comment]
Not by default. You can either add a pull request where you could add this feature to save it directly to the desired path, or just use the approach below:

```
import 'dart:io';

void copyAndMoveFile(String sourcePath, String destinationPath) async {
  final sourceFile = File(sourcePath);
  final newFile = await sourceFile.copy(destinationPath);
  await sourceFile.delete();
  print('File moved to: ${newFile.path}');
}

void main() {
  String oldFilePath = '/path/to/old/file.txt';
  String newFilePath = '/path/to/new/directory/file.txt';
  
  copyAndMoveFile(oldFilePath, newFilePath);
}

```
